### ISSUE TITLE
Table Border 

### ISSUE THREAD

**Issue by BugDiver** [demoV/Call-Break#2]
there is a white border can be see in the table bt its not visible for whole table. 
<img width="1440" alt="screenshot 2016-04-19 08 20 55" src="https://cloud.githubusercontent.com/assets/15309877/14626348/18b4cc34-0608-11e6-9183-a5478c72c7c6.png">

**Comment by AdarshSandilya** [comment]
check again ..i have checked ..but i found all things are fine .

**Comment by BugDiver** [comment]
yeah u r right. i think it's  a random issue. sometimes we get it, sometimes not.
